Added update-main-full, update-main-new, and update-main-old

diff --git a/.local/bin/courseTools b/.local/bin/courseTools
--- a/.local/bin/courseTools
+++ b/.local/bin/courseTools
@@ -12,27 +12,33 @@ echoHelpMessage () {
   echo "  Specified directories should be the direct parent of the info.json file."
   echo
   echo "Available Options:"
-  echo "  -c, --clean                 Remove all files except for .pdf and .tex. These"
-  echo "                              usually come from compiling tex files with pdflatex"
-  echo "  -C, --full-clean            Remove all files except for .tex. These usually"
-  echo "                              come from compiling tex files with pdflatex"
-  echo "  -f, --create-figure         Takes a single argument as a path to a figure template."
-  echo "                              Copies the template into the next figure in the"
-  echo "                              current course's notes/figures/ directory."
-  echo "  -F, --create-basic-figure   Copies the basic_figure.tex template from the templates/"
-  echo "                              directory into the next figure in the current course's"
-  echo "                              notes/figures/ directory."
-  echo "  -l, --create-lecture        Takes a single argument as a path to a lecture template."
-  echo "                              Copies the template into the next lecture in the"
-  echo "                              current course's notes/ directory."
-  echo "  -L, --create-basic-lecture  Copies the basic_lecture.tex template from the templates/"
-  echo "                              directory into the next lecture in the current course's"
-  echo "                              notes/ directory."
-  echo "  -a, --auto-course           Read course information from info.json files in course"
-  echo "                              directories and automatically update current course if"
-  echo "                              applicable"
-  echo "  -s, --set-course DIRECTORY  Sets the current course to DIRECTORY. DIRECTORY must be"
-  echo "                              a child of \$CURRCOURSE environment variable."
+  echo "  -c, --clean                   Remove all files except for .pdf and .tex. These"
+  echo "                                usually come from compiling tex files with pdflatex"
+  echo "  -C, --full-clean              Remove all files except for .tex. These usually"
+  echo "                                come from compiling tex files with pdflatex"
+  echo "  -f, --create-figure           Takes a single argument as a path to a figure template."
+  echo "                                Copies the template into the next figure in the"
+  echo "                                current course's notes/figures/ directory."
+  echo "  -F, --create-basic-figure     Copies the basic_figure.tex template from the templates/"
+  echo "                                directory into the next figure in the current course's"
+  echo "                                notes/figures/ directory."
+  echo "  -l, --create-lecture          Takes a single argument as a path to a lecture template."
+  echo "                                Copies the template into the next lecture in the"
+  echo "                                current course's notes/ directory."
+  echo "  -L, --create-basic-lecture    Copies the basic_lecture.tex template from the templates/"
+  echo "                                directory into the next lecture in the current course's"
+  echo "                                notes/ directory."
+  echo "  -a, --auto-course             Read course information from info.json files in course"
+  echo "                                directories and automatically update current course if"
+  echo "                                applicable"
+  echo "  -s, --set-course [DIRECTORY]  Sets the current course to DIRECTORY. DIRECTORY must be"
+  echo "                                a child of \$CURRCOURSE environment variable."
+  echo "      --update-main-full        Updates the main.tex file to include all lectures in"
+  echo "                                the shared directory."
+  echo "      --update-main-new [n]     Updates the main.tex file to include n lectures in the"
+  echo "                                shared directory, including the newest lectures first."
+  echo "      --update-main-old [n]     Updates the main.tex file to include n lectures in the"
+  echo "                                shared directory, including the oldest lectures first."
 }
 
 if [[ -d "$1" ]]; then
@@ -47,7 +53,7 @@ else
   courseDirectory=$(courseInfo --path)
 fi
 
-VALID_ARGS=$(getopt -o hcCf:Fl:Las: --long clean,full-clean,create-figure:,create-basic-figure,create-lecture:,create-basic-lecture,auto-course,set-course: -- "$@")
+VALID_ARGS=$(getopt -o hcCf:Fl:Las: --long clean,full-clean,create-figure:,create-basic-figure,create-lecture:,create-basic-lecture,auto-course,set-course:,update-main-full,update-main-new:,update-main-old: -- "$@")
 if [[ $? -ne 0 ]]; then
   exit 1;
 fi
@@ -177,6 +183,97 @@ while [ : ]; do
         title=$(courseInfo --title)
         short=$(courseInfo --short)
         notify-send "Current Course Unchanged" "$short - $title"
+      fi
+      shift
+      shift
+      ;;
+
+    --update-main-full)
+      startLineNumber=$(grep -n "% start lectures" "$courseDirectory/notes/main.tex" | cut -d : -f 1)
+      if ! [[ "$startLineNumber" =~ ^[0-9]+$ ]] ; then
+        echo "error: couldn't find start of lectures in main.tex"
+        exit 1
+      fi
+      endLineNumber=$(grep -n "% end lectures" "$courseDirectory/notes/main.tex" | cut -d : -f 1)
+      if ! [[ "$endLineNumber" =~ ^[0-9]+$ ]] ; then
+        echo "error: couldn't find end of lectures in main.tex"
+        exit 1
+      fi
+      if [[ $(($startLineNumber)) -ge $(($endLineNumber)) ]]; then
+        echo "error: end of lectures exists before start of lectures"
+        exit 1
+      fi
+      if ! [[ $(($startLineNumber + 1)) -eq $(($endLineNumber)) ]]; then
+        sed -i "$(($startLineNumber + 1)),$(($endLineNumber - 1))d" "$courseDirectory/notes/main.tex"
+      fi
+      mapfile -t fileNames < <(find "$(courseInfo --path)/notes" -mindepth 1 -maxdepth 1 -name '*.tex' ! -name 'main.tex' | sed 's/.*\/\([^\.]*\)\.tex/\1/' | sort)
+      for i in ${!fileNames[@]}; do
+        sed -i "$(($startLineNumber + 1 + $i))i\  \\\input{${fileNames[$i]}}" "$courseDirectory/notes/main.tex"
+      done
+      shift
+      ;;
+
+    --update-main-new)
+      startLineNumber=$(grep -n "% start lectures" "$courseDirectory/notes/main.tex" | cut -d : -f 1)
+      if ! [[ "$startLineNumber" =~ ^[0-9]+$ ]] ; then
+        echo "error: couldn't find start of lectures in main.tex"
+        exit 1
+      fi
+      endLineNumber=$(grep -n "% end lectures" "$courseDirectory/notes/main.tex" | cut -d : -f 1)
+      if ! [[ "$endLineNumber" =~ ^[0-9]+$ ]] ; then
+        echo "error: couldn't find end of lectures in main.tex"
+        exit 1
+      fi
+      if [[ $(($startLineNumber)) -ge $(($endLineNumber)) ]]; then
+        echo "error: end of lectures exists before start of lectures"
+        exit 1
+      fi
+      if ! [[ $(($startLineNumber + 1)) -eq $(($endLineNumber)) ]]; then
+        sed -i "$(($startLineNumber + 1)),$(($endLineNumber - 1))d" "$courseDirectory/notes/main.tex"
+      fi
+      n=$2
+      mapfile -t fileNames < <(find "$(courseInfo --path)/notes" -mindepth 1 -maxdepth 1 -name '*.tex' ! -name 'main.tex' | sed 's/.*\/\([^\.]*\)\.tex/\1/' | sort)
+      if [[ ${#fileNames[@]} -gt $n ]]; then
+        for i in $(seq 0 $(($n - 1))); do
+          sed -i "$(($startLineNumber + 1 + $i))i\  \\\input{${fileNames[$((${#fileNames[@]} - $n + $i))]}}" "$courseDirectory/notes/main.tex"
+        done
+      else
+        for i in ${!fileNames[@]}; do
+          sed -i "$(($startLineNumber + 1 + $i))i\  \\\input{${fileNames[$i]}}" "$courseDirectory/notes/main.tex"
+        done
+      fi
+      shift
+      shift
+      ;;
+
+    --update-main-old)
+      startLineNumber=$(grep -n "% start lectures" "$courseDirectory/notes/main.tex" | cut -d : -f 1)
+      if ! [[ "$startLineNumber" =~ ^[0-9]+$ ]] ; then
+        echo "error: couldn't find start of lectures in main.tex"
+        exit 1
+      fi
+      endLineNumber=$(grep -n "% end lectures" "$courseDirectory/notes/main.tex" | cut -d : -f 1)
+      if ! [[ "$endLineNumber" =~ ^[0-9]+$ ]] ; then
+        echo "error: couldn't find end of lectures in main.tex"
+        exit 1
+      fi
+      if [[ $(($startLineNumber)) -ge $(($endLineNumber)) ]]; then
+        echo "error: end of lectures exists before start of lectures"
+        exit 1
+      fi
+      if ! [[ $(($startLineNumber + 1)) -eq $(($endLineNumber)) ]]; then
+        sed -i "$(($startLineNumber + 1)),$(($endLineNumber - 1))d" "$courseDirectory/notes/main.tex"
+      fi
+      n=$2
+      mapfile -t fileNames < <(find "$(courseInfo --path)/notes" -mindepth 1 -maxdepth 1 -name '*.tex' ! -name 'main.tex' | sed 's/.*\/\([^\.]*\)\.tex/\1/' | sort)
+      if [[ ${#fileNames[@]} -gt $n ]]; then
+        for i in $(seq 0 $(($n - 1))); do
+          sed -i "$(($startLineNumber + 1 + $i))i\  \\\input{${fileNames[$i]}}" "$courseDirectory/notes/main.tex"
+        done
+      else
+        for i in ${!fileNames[@]}; do
+          sed -i "$(($startLineNumber + 1 + $i))i\  \\\input{${fileNames[$i]}}" "$courseDirectory/notes/main.tex"
+        done
       fi
       shift
       shift
